MODEL_ROUTING = {
    "parser": "gpt-5-nano",
    "cartographer": "gpt-5-nano",
    "novelty_scorer": "gpt-5-nano",
    "saturation_scorer": "gpt-5-nano",
    "conflict_scorer": "gpt-5-nano",
    "feasibility_scorer": "gpt-5-mini",
    "impact_forecaster": "gpt-5-mini",
    "evidence_quality_scorer": "gpt-5-nano",
    "score_aggregator": "code",
    "mutator": "gpt-5",
    "variant_rescorer": "gpt-5-mini",
    "ranker": "code",
    "pareto_curator": "code + gpt-5-nano",
    "strategist": "gpt-5",
    "group_identifier": "gpt-5-nano",
    "group_emulator": "gpt-5-mini",
    "trajectory_synth": "gpt-5",
    "groundedness_check": "gpt-5-nano",
}
